Update locality records
whosonfirst-data/whosonfirst-data-admin-by pull request #13
Opened 2023-06-28 22:24 UTC by stepps00

This PR adds polygons to the locality of Brest. The existing point geometries were stored as alt files, and existing label centroids were kept as-is.

All of the locality points that fall within the new locality polygons look to be neighbourhoods, so they were superseded into new neighbourhood records (rather than flagged as funky). This PR needs to be PIP'd once approved.

2023-06-28 22:31 UTC, stepps00 commented
![Screenshot 2023-06-28 at 3 29 12 PM](https://github.com/whosonfirst-data/whosonfirst-data-admin-by/assets/18567700/e481e734-8d97-46cb-a775-2320f95db536)

2023-06-28 23:34 UTC, nvkelso commented on data/186/399/110/1/1863991101.geojson
> +    "wof:supersedes":[],
Needs supersedes ID listed, please

2023-06-28 23:34 UTC, nvkelso requested changes
Same supersedes comment as the other PRs (for each record, I only noted 1 example).

2023-06-29 00:03 UTC, nvkelso approved these changes
Thanks!

2023-06-30 03:34 UTC, merged